import base64
import logging
import os
from datetime import datetime, timezone

from dotenv import load_dotenv
from github import Github, GithubException

load_dotenv()

logger = logging.getLogger("devloop.github_client")

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO = os.getenv("GITHUB_REPO", "")
GITHUB_BASE_BRANCH = os.getenv("GITHUB_BASE_BRANCH", "main")


def _get_client(token: str = None) -> Github:
    t = token or GITHUB_TOKEN
    if not t:
        raise ValueError("GITHUB_TOKEN not set in environment")
    return Github(t)


def fetch_file(repo_name: str, filepath: str, branch: str = None, token: str = None) -> str:
    branch = branch or GITHUB_BASE_BRANCH
    logger.info("Fetching %s from %s@%s", filepath, repo_name, branch)
    try:
        g = _get_client(token)
        repo = g.get_repo(repo_name)
        content = repo.get_contents(filepath, ref=branch)
        decoded = base64.b64decode(content.content).decode("utf-8")
        logger.info("Fetched %s (%d bytes)", filepath, len(decoded))
        return decoded
    except GithubException as e:
        logger.error("GitHub error fetching %s: %s", filepath, e)
        raise
    except Exception as e:
        logger.error("Unexpected error fetching %s: %s", filepath, e)
        raise


def create_branch(repo_name: str, branch_name: str, token: str = None) -> str:
    logger.info("Creating branch %s in %s", branch_name, repo_name)
    try:
        g = _get_client(token)
        repo = g.get_repo(repo_name)
        base_ref = repo.get_branch(GITHUB_BASE_BRANCH)
        repo.create_git_ref(f"refs/heads/{branch_name}", base_ref.commit.sha)
        logger.info("Branch %s created from %s", branch_name, GITHUB_BASE_BRANCH)
        return branch_name
    except GithubException as e:
        logger.error("GitHub error creating branch %s: %s", branch_name, e)
        raise
    except Exception as e:
        logger.error("Unexpected error creating branch %s: %s", branch_name, e)
        raise


def commit_patch(
    repo_name: str,
    branch: str,
    filepath: str,
    new_content: str,
    message: str,
    token: str = None,
) -> str:
    logger.info("Committing patch to %s on branch %s", filepath, branch)
    try:
        g = _get_client(token)
        repo = g.get_repo(repo_name)
        current = repo.get_contents(filepath, ref=branch)
        result = repo.update_file(
            path=filepath,
            message=message,
            content=new_content,
            sha=current.sha,
            branch=branch,
        )
        commit_sha = result["commit"].sha
        logger.info("Committed patch: %s", commit_sha)
        return commit_sha
    except GithubException as e:
        logger.error("GitHub error committing patch to %s: %s", filepath, e)
        raise
    except Exception as e:
        logger.error("Unexpected error committing patch to %s: %s", filepath, e)
        raise


def open_pr(
    repo_name: str,
    branch: str,
    title: str,
    body: str,
    token: str = None,
) -> str:
    logger.info("Opening PR from %s in %s", branch, repo_name)
    try:
        g = _get_client(token)
        repo = g.get_repo(repo_name)
        pr = repo.create_pull(
            title=title,
            body=body,
            head=branch,
            base=GITHUB_BASE_BRANCH,
        )
        logger.info("PR opened: %s", pr.html_url)
        return pr.html_url
    except GithubException as e:
        logger.error("GitHub error opening PR from %s: %s", branch, e)
        raise
    except Exception as e:
        logger.error("Unexpected error opening PR from %s: %s", branch, e)
        raise


def make_branch_name() -> str:
    ts = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    return f"fix/devloop-{ts}"


def build_pr_body(
    error_message: str,
    root_cause: str,
    fix_summary: str,
    test_results: dict,
    filename: str,
) -> str:
    test_status = "✅ Passing" if test_results.get("passed") else "❌ Failing"
    test_output = test_results.get("output", "No output captured")
    duration = test_results.get("duration", 0)

    return f"""## Error Summary
**File:** `{filename}`
**Error:** {error_message}

## Root Cause
{root_cause}

## Fix Applied
{fix_summary}

## Test Results
**Status:** {test_status}
**Duration:** {duration:.2f}s

```
{test_output[:3000]}
```

---
*Automatically generated by [DevLoop](https://github.com/devloop)*
"""
